### ISSUE TITLE
how to config htmlhint bin and config file path

### ISSUE THREAD

**Issue by imwtr** [iyuuya/htmlhint-plugin#2]
**path to htmlhint bin**: `node_modules\htmlhint\bin\htmlhint`
**htmlhint config file path**: `.htmlhintrc`

seems to be not working, no lints or messages

**Comment by imwtr** [comment]
I resolved it by change the htmlhint bin by `D:\Program Files\nodejs\node.exe C:\Users\e470\AppData\Roaming\npm\node_modules\htmlhint\bin\htmlhint`

**Comment by iyuuya** [comment]
The assumption was thought of `/path/to/node_modules/.bin/htmlhint` whether it was `npm install htmlhint - g` or` npm install htmlhint --save-dev`.

In the case of Windows, since `.bin/htmlhint` can not be granted execution privilege like linux, .cmd file is generated. 
Setting that path may make it smarter.

e.g.
```
/path/to/node_modules/.bin/htmlhint.cmd
```

I have not developed it on Windows, so it is unclear what is certain.
